### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by 111122-lab** [thanosvlo/MARL-for-Anatomical-Landmark-Detection#3]
Hi,thanks for your share,
when I run the code DQN_eval,there is a code :NotImplementedError.
my tensorflow version is 1.14.0 and tensorpack version is 0.9.5

**Comment by a310694487** [comment]
I got the same error .....

**Comment by a310694487** [comment]
**The complete error message is**　
Traceback (most recent call last):
  File "DQN.py", line 321, in <module>
    launch_train_with_config(config, SimpleTrainer())
  File "/home/paulson/anaconda3/lib/python3.7/site-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "/home/paulson/anaconda3/lib/python3.7/site-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/home/paulson/anaconda3/lib/python3.7/site-packages/tensorpack/graph_builder/model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "/home/paulson/anaconda3/lib/python3.7/site-packages/tensorpack/graph_builder/model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by 111122-lab** [comment]
this maybe caused by the tensorpack_version,I use the version 0.9.5




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Paulson"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 晚上9:47
收件人:&nbsp;"thanosvlo/MARL-for-Anatomical-Landmark-Detection"<MARL-for-Anatomical-Landmark-Detection@noreply.github.com&gt;;
抄送:&nbsp;"renjingfang"<1271179043@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thanosvlo/MARL-for-Anatomical-Landmark-Detection] NotImplementedError (#3)




I got the same error .....

**Comment by ming-527** [comment]
I got the same error,too. How to solve this problem?

**Comment by dpamgautam** [comment]
> Hi,thanks for your share,
> when I run the code DQN_eval,there is a code :NotImplementedError.
> my tensorflow version is 1.14.0 and tensorpack version is 0.9.5

Hi, did u resolve this issue?
Im also getting exactly the same error

**Comment by dpamgautam** [comment]
@111122-lab  @a310694487  @ming-527  

has anyone solved this issue?
Im also getting the same error.

**Comment by zzu0654** [comment]
Traceback (most recent call last):
  File "DQN.py", line 276, in <module>
    task='train',agents=args.agents,reward_strategy=args.reward_strategy)
  File "/data/zhcy/Projects/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 174, in __init__
    agents=self.agents)
  File "/data/zhcy/Projects/MARL-for-Anatomical-Landmark-Detection-master/dataReader.py", line 170, in __init__
    self.image_files = [line.split('\n')[0] for line in open(files_list[0])]
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper

**Comment by zzu0654** [comment]
Have you encountered this problem?
Traceback (most recent call last):
File "DQN.py", line 276, in 
task='train',agents=args.agents,reward_strategy=args.reward_strategy)
File "/data/zhcy/Projects/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 174, in init
agents=self.agents)
File "/data/zhcy/Projects/MARL-for-Anatomical-Landmark-Detection-master/dataReader.py", line 170, in init
self.image_files = [line.split('\n')[0] for line in open(files_list[0])]
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper

**Comment by gaomeng-kang** [comment]
@111122-lab @a310694487 @ming-527 @dpamgautam 
sorry to bother,have u solved this? i got the same error

**Comment by tjdals638** [comment]
@111122-lab @a310694487 @ming-527 @dpamgautam @gaomeng-kang 
try tensorpack==0.9.0

**Comment by gaomeng-kang** [comment]
@tjdals638 
> try tensorpack==0.9.0
thank u so much！that works！
